### ISSUE TITLE
ModuleNotFoundError: No module named '_gdal_array'

### ISSUE THREAD

**Issue by system123** [camptocamp/docker-python-gis#10]
When calling .ReadAsArray() I get the following error:

```
Traceback (most recent call last):
  ....
  File "/src/generate_factors.py", line 35, in read_pixels
    data = np.array(band.ReadAsArray(xoff, yoff, w, h))
  File "/usr/local/lib/python3.6/site-packages/osgeo/gdal.py", line 2536, in ReadAsArray
    from . import gdalnumeric
  File "/usr/local/lib/python3.6/site-packages/osgeo/gdalnumeric.py", line 1, in <module>
    from osgeo.gdal_array import *
  File "/usr/local/lib/python3.6/site-packages/osgeo/gdal_array.py", line 28, in <module>
    _gdal_array = swig_import_helper()
  File "/usr/local/lib/python3.6/site-packages/osgeo/gdal_array.py", line 20, in swig_import_helper
    import _gdal_array
ModuleNotFoundError: No module named '_gdal_array'
```

**Comment by Tartomas** [comment]
Hello !
Do you have an update on this issue? 
Best
